model1:
  input_size: 2352
  hidden_size: [256,256,128,128]
  output_size: 10
  num_heads: 5
model2:
  input_size: 2352
  hidden_size: [256,256,128,128]
  output_size: 10
  num_heads: 4
model3:
  input_size: 2352
  hidden_size: [256,256,128,128]
  output_size: 10
  num_heads: 3
model4:
  input_size: 2352
  hidden_size: [256,256,128,128]
  output_size: 10
  num_heads: 2
model5:
  input_size: 2352
  hidden_size: [128,128]
  output_size: 10
  num_heads: 4